import { usePage } from '@inertiajs/react';

const translations = {
    pt: {
        home: 'Home',
        sobre: 'Sobre',
        nossosVinhos: 'Nossos Vinhos',
        enoturismo: 'Enoturismo',
        contato: 'Contato',
        blog: 'Blog',
        lojaVirtual: 'Loja Virtual',
        whatsapp: 'WhatsApp',
        verMapa: 'Ver Mapa',
        nossasRedes: 'Nossas redes',
        marcas: 'Marcas',
        categorias: 'Categorias',
        sustentabilidade: 'Sustentabilidade',
        vinhos: 'Vinhos',
        politicaPrivacidade: 'Política de Privacidade',
        todosOsDireitosReservados: 'Todos os direitos reservados',
        desenvolvidoPor: 'Desenvolvido por',
        conhecaNossosVinhos: 'Conheça nossos vinhos',
        conheca: 'Conheça',
        verLinhaDoTempo: 'Ver linha do Tempo',
        liEAceito: 'Li e aceito a',
        enviar: 'Enviar',
        enviarMensagem: 'Enviar Mensagem',
        endereco1: 'Via dos Parreirais, S/Nº',
        endereco2: 'Santa Lúcia - Vale dos Vinhedos',
        endereco3: 'Bento Gonçalves - RS - Brasil',
        endereco4: 'CEP 95711-000',
        localizacao: 'Localização',
        composicaoDoSolo: 'Composição do solo',
        clima: 'Clima',
        arquitetura: 'Arquitetura',
        agendeSuaExperiencia: 'Agende sua Experiência',
        fale: 'Fale',
        conosco: 'Conosco',
        endereco: 'Endereço',
        selecioneAreaContato: 'Selecione a área de contato:',
        geral: 'Geral',
        comercial: 'Comercial',
        nomeCompleto: 'Nome completo',
        email: 'E-mail',
        telefone: 'Telefone',
        digiteAqui: 'Digite aqui...',
        sucesso: 'Sucesso!',
        suaMensagemFoiEnviada: 'Sua mensagem foi enviada.',
        verMaisVinhos: 'Ver mais vinhos.',
        comprarAgora: 'Comprar Agora',
        filtros: 'Filtros',
        aplicarFiltros: 'Aplicar Filtros',
        destaques: 'Destaques',
        baixarFicha: 'Baixar Ficha Técnica',
        fichaTecnica: 'Ficha Técnica',
        colheitas: 'Colheitas',
        areaRestrita: 'Área Restrita'
    },
    en: {
        home: 'Home',
        sobre: 'About',
        nossosVinhos: 'Our Wines',
        enoturismo: 'Wine Tourism',
        contato: 'Contact',
        blog: 'Blog',
        lojaVirtual: 'Virtual Store',
        whatsapp: 'WhatsApp',
        verMapa: 'View Map',
        nossasRedes: 'Our medias',
        marcas: 'Brands',
        categorias: 'Categories',
        sustentabilidade: 'Sustainability',
        vinhos: 'Wines',
        politicaPrivacidade: 'Privacy Policy',
        todosOsDireitosReservados: 'All rights reserved',
        desenvolvidoPor: 'Developed by',
        conhecaNossosVinhos: 'Discover our wines',
        conheca: 'Discover',
        verLinhaDoTempo: 'View Timeline',
        liEAceito: 'I have read and accept the',
        enviar: 'Send',
        enviarMensagem: 'Send Message',
        endereco1: 'Via dos Parreirais, S/Nº',
        endereco2: 'Santa Lúcia - Vale dos Vinhedos',
        endereco3: 'Bento Gonçalves - RS - Brazil',
        endereco4: 'ZIP 95711-000',
        localizacao: 'Location',
        composicaoDoSolo: 'Soil Composition',
        clima: 'Climate',
        arquitetura: 'Architecture',
        agendeSuaExperiencia: 'Schedule your experience',
        fale: 'Talk',
        conosco: 'to Us',
        endereco: 'Address',
        selecioneAreaContato: 'Select the contact area:',
        geral: 'General',
        comercial: 'Commercial',
        nomeCompleto: 'Full name',
        email: 'E-mail',
        telefone: 'Phone',
        digiteAqui: 'Type here...',
        sucesso: 'Success!',
        suaMensagemFoiEnviada: 'Your message has been sent.',
        verMaisVinhos: 'See more wines.',
        comprarAgora: 'Buy Now',
        filtros: 'Filters',
        aplicarFiltros: 'Apply Filters',
        destaques: 'Highlights',
        baixarFicha: 'Download Technical Sheet',
        fichaTecnica: 'Technical Sheet',
        colheitas: 'Harvests',
        areaRestrita: 'Restrict Area'
    }
};

export function useLang() {
  const { idioma } = usePage().props;

  return (key) => translations[idioma]?.[key] || key;
}